#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config normal_border_color "#30365f"
bspc config active_border_color "#5ccc96"
bspc config focused_border_color "#b3a1e6"

bspc config border_width         0
bspc config window_gap          48

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a firefox desktop='^2'
bspc rule -a Zathura desktop='^2' follow=on
bspc rule -a Zathura state=tiled
