" initialize plugins
call plug#begin('~/.config/nvim/plugged')
source ~/.config/nvim/config/plugins.vim
call plug#end()

filetype plugin indent on
syntax enable

source ~/.config/nvim/config/general.vim
source ~/.config/nvim/config/mappings.vim
source ~/.config/nvim/config/plugin-mappings.vim
source ~/.config/nvim/config/theme.vim
