# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.zinit/bin/zinit.zsh
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

autoload -Uz compinit
compinit

# zsh plugins
zinit light Aloxaf/fzf-tab
zinit light zdharma/fast-syntax-highlighting
zinit load zdharma/history-search-multi-word
zinit light zsh-users/zsh-autosuggestions

zinit ice from"gh-r" as"program"
zinit load junegunn/fzf-bin

zinit ice wait lucid
zinit load hlissner/zsh-autopair

zinit ice depth=1; zinit light romkatv/powerlevel10k

# aliases
alias ls='ls -FG'
alias l.='ls -dahG .*'
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"

alias ip="ifconfig -a | perl -nle '/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias g++17='g++ -std=c++17'
alias pip='pip3'
alias python='python3'

# exports
export TERM="xterm-256color"
export VISUAL=nvim
export EDITOR=nvim
export PATH=$PATH:$HOME/go/bin

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
