#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







  xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







  xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# set correct pointer
xsetroot -cursor_name left_ptr

# set background wallpaper
nitrogen --restore &
picom -f &

# set correct dpi
echo 'Xft.dpi: 118' | xrdb

# set correct mouse sensitivity                                                \/       \/
xinput set-prop "pointer:Glorious Model O" "Coordinate Transformation Matrix" 0.5 0 0 0 0.5 0 0 0 1

# lock screen on start up
betterlockscreen -l dimblur

# start bspwm
exec bspwm
